# Builds and published Dashy's documentation website
name: ğŸ“ Build Docs Site
on:
  workflow_dispatch:
  push:
    branches: [ WEBSITE/docs-site-source ]
jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/WEBSITE/docs-site-source'
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@5c7944e73c4c2a096b17a9cb74d65b6c2bbafbde # v2.9.1
        with:
          egress-policy: audit

      - uses: actions/checkout@61b9e3751b92087fd0b06925ba6dd6314e06f089 # master
      - uses: redkubes/docusaurus-deploy-action@e3c1d7f8732f8790ea45ac7ded561a8535bdbe13 # v1
        with:
          source-folder: ./
          git-user: ${{ github.actor }}
          git-password: ${{ secrets.GITHUB_TOKEN }}
          deployment-branch: gh-pages
