# Close any issue that does not match any of the issue templates
name: ğŸ¯ Close Incomplete Issues
on:
  issues:
    types: [opened, edited]
jobs:
  auto_close_issues:
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@5c7944e73c4c2a096b17a9cb74d65b6c2bbafbde # v2.9.1
        with:
          egress-policy: audit

      - name: Checkout
        uses: actions/checkout@50fbc622fc4ef5163becd7fab6573eac35f8462e # v1.2.0
      - name: Automatically close issues that don't follow the issue template
        uses: lucasbento/auto-close-issues@667e4f3cd71f2760a3869680944b8df55325b005 # v1.0.2
        with:
          github-token: ${{ secrets.BOT_GITHUB_TOKEN || secrets.GITHUB_TOKEN }}
          closed-issues-label: 'ğŸ™ Auto-Closed'
          issue-close-message: |
            Hello @${issue.user.login} ğŸ‘‹
            Unfortunately your issue does not follow the format outlined in the template, and has therefore been auto-closed.
            To ensure that all relevant info is included, please either update or recreate your issue, and complete the sub-headings provided.
            Thank you :)
