name: ğŸ³ Build + Publish Multi-Platform Image

on:
  workflow_dispatch:
  push:
    branches: ['master']
    tags: ['*.*']
    paths:
      - '**.js'
      - 'src/**'
      - 'public/**'
      - 'services/**'
      - '.github/workflows/docker-build-publish.yml'
      - 'Dockerfile'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  packages: write

env:
  DH_IMAGE: ${{ secrets.DOCKER_REPO }}
  GH_IMAGE: ${{ github.repository_owner }}/${{ github.event.repository.name }}

jobs:
  docker:
    runs-on: ubuntu-latest
    permissions: { contents: read, packages: write }
    if: "!contains(github.event.head_commit.message, '[ci-skip]')"

    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@5c7944e73c4c2a096b17a9cb74d65b6c2bbafbde # v2.9.1
      with:
        egress-policy: audit

    - name: ğŸ›ï¸ Checkout Repo
      uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0

    - name: ğŸ”– Get App Version
      uses: tyankatsu0105/read-package-version-actions@b660c21be1531c1ad23c0bbfb72dfe64c9af05a6 # v1
      id: package-version

    - name: ğŸ—‚ï¸ Make Docker Meta
      id: meta
      uses: docker/metadata-action@b2391d37b4157fa4aa2e118d643f417910ff3242 # v3.8.0
      with:
        images: |
          ${{ env.DH_IMAGE }}
          ghcr.io/${{ env.GH_IMAGE }}
        tags: |
          type=ref,event=tag
          type=semver,pattern={{version}},enable=false
          type=semver,pattern={{major}}.x
          type=raw,value=latest
        flavor: |
          latest=false
        labels: |
          maintainer=Lissy93
          org.opencontainers.image.title=Dashy
          org.opencontainers.image.description=A self-hosted startpage for your server
          org.opencontainers.image.documentation=https://dashy.to/docs
          org.opencontainers.image.authors=Alicia Sykes
          org.opencontainers.image.licenses=MIT

    - name: ğŸ”§ Set up QEMU
      uses: docker/setup-qemu-action@27d0a4f181a40b142cce983c5393082c365d1480 # v1.2.0
      with:
        platforms: linux/amd64,linux/arm64,linux/arm/v7

    - name: ğŸ”§ Set up Docker Buildx
      uses: docker/setup-buildx-action@885d1462b80bc1c1c7f0b00334ad271f09369c55 # v2.10.0
      with:
        use-buildkit: true
        buildkit-daemon-opts: "--oci-worker-no-process-sandbox"

    - name: ğŸ‘€ Inspect builder
      run: |
        echo "Name:      ${{ steps.buildx.outputs.name }}"
        echo "Endpoint:  ${{ steps.buildx.outputs.endpoint }}"
        echo "Status:    ${{ steps.buildx.outputs.status }}"
        echo "Flags:     ${{ steps.buildx.outputs.flags }}"
        echo "Platforms: ${{ steps.buildx.outputs.platforms }}"

    - name: ğŸ”‘ Login to DockerHub
      uses: docker/login-action@465a07811f14bebb1938fbed4728c6a1ff8901fc # v2.2.0
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: ğŸ”‘ Login to GitHub Container Registry
      uses: docker/login-action@465a07811f14bebb1938fbed4728c6a1ff8901fc # v2.2.0
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: ğŸš¦ Check Registry Status
      uses: crazy-max/ghaction-docker-status@b10dd9c1fa62075808e5a6102469620d39917c41 # v1.2.0

    - name: âš’ï¸ Build and push
      uses: docker/build-push-action@1104d471370f9806843c095c1db02b5a90c5f8b6 # v3.3.1
      with:
        context: .
        file: ./Dockerfile
        platforms: linux/amd64,linux/arm64,linux/arm/v7
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        push: true
