name: ğŸ“ Update Documentation

# This will run whenever the /docs directory in master branch is updated,
# or if the workflow is manually dispatched, plus a sync check on Sun at 03:30 UTC
on:
  workflow_dispatch:
  schedule:
    - cron: '30 3 * * 0'
  push:
    branches:
      - master
    paths:
      - 'docs/**'


# Jobs to be run:
# 1. Checkout master branch
# 2. Checkout website source code branch
# 3. Install Python
# 4. Copy /docs from master to website branch
# 5. Run the script which processes documentation
# 6. Commit and push updated docs to the website source code branch
permissions:
  contents: read

jobs:
  update-docs:
    permissions:
      contents: write  # for Git to git push
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@5c7944e73c4c2a096b17a9cb74d65b6c2bbafbde # v2.9.1
        with:
          egress-policy: audit

      - name: Checkout master branch ğŸ›ï¸
        uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5 # v2.7.0
        with:
          path: 'master-docs'

      - name: Checkout WEBSITE/docs-site-source branch ğŸ›ï¸
        uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5 # v2.7.0
        with:
          ref: 'WEBSITE/docs-site-source'
          path: 'website-docs'

      - name: Install Python ğŸ
        uses: actions/setup-python@e9aba2c848f5ebd159c070c61ea2c4e2b122355e # v2.3.4
        with:
          python-version: '3.x'

      - name: Run script to update documentation ğŸª„
        working-directory: website-docs
        run: |
          cp -r ../master-docs/docs ./
          python ./do-markdown-magic.py
        
      - name: Commit changes ğŸš€
        run: |
          cd website-docs
          git config --local user.email "liss-bot@d0h.co"
          git config --local user.name "Liss-Bot"
          git add docs
          git commit -m "Update documentation" || echo "No changes to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.BOT_GITHUB_TOKEN || secrets.GITHUB_TOKEN }}
